[envs.test]
dependencies = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "pytest-xdist>=3.6.1",
    "pytest-asyncio>=0.26.0",
    "coverage[toml]>=7.6.12",
]

[envs.test.scripts]
run = "pytest {args:tests}"
cov = "pytest --cov-report=term-missing:skip-covered --cov-report=html --cov-report=xml --cov-fail-under=80 --cov=src/claif {args:tests}"
no-cov = "pytest --no-cov {args:tests}"