remote_theme: just-the-docs/just-the-docs
title: Claif - Command-Line Artificial Intelligence Framework
description: >-
  Claif (Command-Line AI Framework) is a unified interface for interacting with various large language models (LLMs) from the command line.
color_scheme: dark
search_enabled: true
aux_links:
  "Claif on GitHub":
    - "https://github.com/twardoch/claif"

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links_active: true

# Footer content
# appears at the bottom of every page of your site
footer_content: "&copy; 2025 Claif. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/blob/main/LICENSE.txt\">MIT license.</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Giscus
giscus_active: true
giscus_repo: "twardoch/claif"
giscus_repo_id: "R_kgDOLX_22Q"
giscus_category: "Announcements"
giscus_category_id: "DIC_kwDOLX_22c4Cg_yS"
giscus_mapping: "pathname"
giscus_strict: "0"
giscus_reactions_enabled: "1"
giscus_emit_metadata: "0"
giscus_input_position: "bottom"
giscus_theme: "preferred_color_scheme"
giscus_lang: "en"
giscus_loading: "lazy"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/