title: Claif - Command-Line Artificial Intelligence Framework
description: >-
  Claif (Command-Line AI Framework) is a unified interface for interacting with various large language models (LLMs) from the command line.
theme: jekyll-theme-minimal
